- name: play-1
  hosts: localhost
  tasks: 
  - name: play-1 and task-1
    ansible.builtin.debug:
      msg: "Hi, I'm learning DevOps Course."
- name: play-2
  hosts: localhost
  tasks:
  - name: play-2 and task-1
    ansbile.builtin.debug:
      msg: "Hi, I'm learning DevOps Course and i'll get job in April this year."