- name: Play-1
  hosts: localhost
  tasks: 
  - name: Play-1 and Task-1
    ansible.builtin.debug:
      msg: Hi, i'm from Rayachoty

- name: Play-2 
  hosts: localhost
  tasks:
  - name: Play-2 and Task-1
    ansible.builtin.debug:
      msg: Hi, i'm in blr now