- name: variables
  hosts: localhost
  vars:
    Course: "DevOps"
    Trainer: "Reddy"
    Duration: "2 months"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, MySelf ReddySekhar and im taking {{Course}} from {{Trainer}} and course durarion is {{Duration}}." 