- name: variables
  hosts: localhost
  vars:
    Name: "ReddySekhar"
    Course: "DevOps"
    Trainer: "SivaKumar"
  tasks:
  - name: print vriable info
    ansible.builtin.debug: # this debug module is like echo command, will print info.
      msg: "Hi, Myself {{Name}} and i'm learning {{Course}} from trainer {{Trainer}}."