- name: variables
  hosts: localhost
  vars:
    Course: "DevOps"
    Tools: "Ansible"
    Duration: "1 Week"
  tasks:
  - name: print override information
    vars:
      Course: "Terraform"
    ansible.bultin.debug:
      msg: "Hi, Iam learning {{Course}} course. Now im practicing {{Tools}} tool and will finish it in {{Duration}}."

  - name: Print variable information
    ansible.builtin.debug:
      msg: "Hi, Iam learning {{Course}} course. Now im practicing {{Tools}} tool and will finish it in {{Duration}}."

