- name: variables
  hosts: localhost
  vars:
    Name: "ReddySekhar"
    Course: "DevOps"
    Tools: "Ansible"
  tasks:
  - name: print the override info.
    vars:
      Course: "Terraform"
    ansible.builtin.debug:
      msg: "Hi, Myself {{Name}} and i joined in {{Course}} course. And currently learning {{Tools}} tool."

  - name: print the info.
    ansible.builtin.debug:
      msg: "Hi, Myself {{Name}} and i joined in {{Course}} course. And currently learning {{Tools}} tool."
  