- name: variables from file
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: print the info
    ansible.builtin.debug:
      msg: "Hi, Iam learning {{Course}} course and currently learning {{Tools}}."