- name: variables
  hosts: localhost
  vars_file:
  - var.yaml
  tasks:
  - name: print the info
    ansible.builtin.debug:
      msg: "Hi, Iam learning {{Course}} course and currently learning {{Tools}}"