- name: Variable from file
  hosts: localhost
  vars_file:
  - vars.yaml
  tasks:
  - name: print variable info
    ansible.builtin.debug:
      msg: "Hi, Iam learning {{Course}} course. Now im practicing {{Tools}} tool and will finish it in {{Duration}}."
