- name: variable from arguments
  hosts: localhost
  tasks:
  - name: print variable info
    ansible.builtin.debug:
      msg: "Hi, Myself {{Name}} and iam learning {{Course}} course. i will get {{Course}} job in April month."