- name: variable preference
  hosts: localhost
  vars:
    Wishes: "Morning from play level variable"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: Wishes
    prompt: please enter Wishes
    private: false
  tasks:
  - name: check variable preference
    vars:
      Wishes: "Morning from task level varaible"
    ansible.builtin.debug:
      msg: Hello, Good {{Wishes}}
  