- name: variables
  hosts: localhost
  vars:
    Course: "DevOps"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: Course
    prompt: please enter the course.
    private: false
  tasks:
  - name: print info from task level
    vars:
      Course: "DevOps"
    ansible.builtin.debug:
      msg: "Hi, iam learning {{Course}}"