- name: data types
  hosts: localhost
  vars:
    Course: "DevOps with AWS"
    Tools: 
    - Linux
    - Shell
    - Ansible
  Experience:
    DevOps: 3
    AWS: 2
    Docker: 1
  RealProject: true
  tasks:
  - name: print variable info
    ansible.builtin.debug:
      msg: "Hi, i'm learning {{Course}} course and the tools covered till now {{Tools}}, for the experience {{Experience}} and its real project {{RealProject}}"