- name: Data types
  hosts: localhost
  vars:
    Course: "DevOps with AWS" # String
    Tools: # List
      - linux
      - Shell
      - Ansible
    Experience: 
      DevOps: 3 # Number
      AWS: 2
      Ansible: 1
    RealProject: true # boolean
  tasks:
  - name: print the datatypes info
    ansible.builtin.debug:
      msg: "Hi, Iam learning {{Course}} course, i have covered {{Tools}} tools. And i have {{Experience}} experience. Its a {{RealProject}} realproject."