- name: Conditions
  hosts: web
  become: yes
  tasks: 
  - name: check user exist or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: yes

  - name: say Hello
    ansible.builtin.debug:
      msg: "Hello"
