- name: conditions
  hosts: localhost
  tasks:
  - name: check the user id existing or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true

  - name: print user inofrmation
    ansible.builtin.debug:
      msg: "user info: {{USER}}"

  - name: create user
    ansible.builtin.command:
    when: USER.rc !=0 
    
  - name: say hello
    ansible.builtin.debug:
      msg: "Hello"