- name: conditions
  hosts: localhost
  vars_prompt:
    - name: number
      prompt: please give the number
      private: yes
  tasks:
  - name: number is less than 10
    ansible.builtin.debug:
      msg: "Given number is {{number}} less than 10"
    when: number | int < 10

  - name: number is greater than 10
    ansible.builtin.debug:
      msg: "Given number is {{number}} greater than 10"
    when: number | int < 10