- name: conditions
  hosts: localhost
  vars_prompt:
    - name: number
      prompt: please give the number
      private: yes
  tasks:
  - name: check the number
    ansible.builtin.debug:
      msg: "Given number is less than 10"
    when: number | int < 10

  - name: check the number
    ansible.builtin.debug:
      msg: "Given number is greater than 10"
    when: number | int < 10