- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.debug:
      msg: "installing packages {{item}}"
    loop:
      - mysql
      - nginx
